### ISSUE TITLE
Server crashing on start

### ISSUE THREAD

**Issue by rjames86** [apexskier/nova-typescript#367]
Just started getting this crash when the typescript language server starts

```
TypeScript Language Server[10:08:24.125000] SyntaxError: Unexpected token < in JSON at position 0

TypeScript Language Server[10:08:24.125000]     at JSON.parse (<anonymous>)

TypeScript Language Server[10:08:24.125000]     at TspClient.processMessage (/Users/USERNAME/Library/Application Support/Nova/Extensions/apexskier.typescript/dependencyManagement/node_modules/typescript-language-server/lib/tsp-client.js:130:30)

TypeScript Language Server[10:08:24.125000]     at Interface.<anonymous> (/Users/USERNAME/Library/Application Support/Nova/Extensions/apexskier.typescript/dependencyManagement/node_modules/typescript-language-server/lib/tsp-client.js:79:56)

TypeScript Language Server[10:08:24.125000]     at Interface.emit (events.js:310:20)

TypeScript Language Server[10:08:24.125000]     at Interface._onLine (readline.js:322:10)

TypeScript Language Server[10:08:24.125000]     at Interface._normalWrite (readline.js:467:12)

TypeScript Language Server[10:08:24.125000]     at Socket.ondata (readline.js:179:10)

TypeScript Language Server[10:08:24.125000]     at Socket.emit (events.js:310:20)

TypeScript Language Server[10:08:24.125000]     at addChunk (_stream_readable.js:286:12)

TypeScript Language Server[10:08:24.125000]     at readableAddChunk (_stream_readable.js:268:9)
```

Please let me know if there's anything else I can do to debug or provide more info

**Comment by apexskier** [comment]
I've upgraded the underlying `typescript-language-server` from v0.5.4 to v0.11.0 ([changelog](https://github.com/typescript-language-server/typescript-language-server/blob/v0.11.0/CHANGELOG.md)). This is a fairly high chance of fixing this specific bug.
